# Generated by Django 5.1 on 2024-08-08 14:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_alter_teammember_email_alter_teammember_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammember',
            name='phone_number',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Enter the correct phone number.', regex='^\\+?\\d+(-\\d+)*$')], verbose_name='Phone Number'),
        ),
    ]
